export const tags = [
  ["Array", "array"],
  ["String", "string"],
  ["Hash Table", "hash-table"],
  ["Dynamic Programming", "dynamic-programming"],
  ["Math", "math"],
  ["Sorting", "sorting"],
  ["Greedy", "greedy"],
  ["Depth-First Search", "depth-first-search"],
  ["Database", "database"],
  ["Breadth-First Search", "breadth-first-search"],
  ["Tree", "tree"],
  ["Binary Search", "binary-search"],
  ["Matrix", "matrix"],
  ["Binary Tree", "binary-tree"],
  ["Two Pointers", "two-pointers"],
  ["Bit Manipulation", "bit-manipulation"],
  ["Stack", "stack"],
  ["Heap (Priority Queue)", "heap-priority-queue"],
  ["Design", "design"],
  ["Graph", "graph"],
  ["Prefix Sum", "prefix-sum"],
  ["Simulation", "simulation"],
  ["Backtracking", "backtracking"],
  ["Counting", "counting"],
  ["Sliding Window", "sliding-window"],
  ["Linked List", "linked-list"],
  ["Union Find", "union-find"],
  ["Ordered Set", "ordered-set"],
  ["Monotonic Stack", "monotonic-stack"],
  ["Enumeration", "enumeration"],
  ["Recursion", "recursion"],
  ["Trie", "trie"],
  ["Divide and Conquer", "divide-and-conquer"],
  ["Binary Search Tree", "binary-search-tree"],
  ["Bitmask", "bitmask"],
  ["Queue", "queue"],
  ["Memoization", "memoization"],
  ["Geometry", "geometry"],
  ["Segment Tree", "segment-tree"],
  ["Topological Sort", "topological-sort"],
  ["Hash Function", "hash-function"],
  ["Game Theory", "game-theory"],
  ["Binary Indexed Tree", "binary-indexed-tree"],
  ["Number Theory", "number-theory"],
  ["Interactive", "interactive"],
  ["String Matching", "string-matching"],
  ["Rolling Hash", "rolling-hash"],
  ["Shortest Path", "shortest-path"],
  ["Data Stream", "data-stream"],
  ["Combinatorics", "combinatorics"],
  ["Randomized", "randomized"],
  ["Monotonic Queue", "monotonic-queue"],
  ["Brainteaser", "brainteaser"],
  ["Merge Sort", "merge-sort"],
  ["Iterator", "iterator"],
  ["Concurrency", "concurrency"],
  ["Doubly-Linked List", "doubly-linked-list"],
  ["Probability and Statistics", "probability-and-statistics"],
  ["Quickselect", "quickselect"],
  ["Bucket Sort", "bucket-sort"],
  ["Suffix Array", "suffix-array"],
  ["Minimum Spanning Tree", "minimum-spanning-tree"],
  ["Counting Sort", "counting-sort"],
  ["Line Sweep", "line-sweep"],
  ["Reservoir Sampling", "reservoir-sampling"],
  ["Eulerian Circuit", "eulerian-circuit"],
  ["Radix Sort", "radix-sort"],
  ["Strongly Connected Component", "strongly-connected-component"],
  ["Rejection Sampling", "rejection-sampling"],
  ["Biconnected Component", "biconnected-component"],
];
