name: run-cron

on:
  schedule:
    - cron: "0 12 * * 0"

  workflow_dispatch:

jobs:
  update-node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3.5.1
        with:
          node-version: "18.x"
      - run: |
          yarn install
          node cron/test.mjs
        env:
          LEETCODE_SESSION_TOKEN: ${{ secrets.LEETCODE_SESSION_TOKEN }}
          LEETCODE_CSRF: ${{ secrets.CSRF }}
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update questions via run-cron GitHub Action
